name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  spec:
    runs-on: ubuntu-latest

    env:
      OPENAI_ACCESS_TOKEN: ${{ secrets.OPENAI_ACCESS_TOKEN}}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Test with RSpec
        env:
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres@localhost:5432/pms_be_test"
          RUBYOPT: "-W:no-deprecated -W:no-experimental" # Suppress Rails 6 deprecation warnings for ruby 2.7
        run: |
          bundle exec rails db:setup
          bundle exec rspec --format documentation

#       - name: Upload test coverage to Codecov
#         uses: codecov/codecov-action@v2
#         with:
#           token: ${{ secrets.CODECOV_TOKEN }}

